# -*- coding: utf-8 -*-
"""Fraud Training.ipynb

Automatically generated by Colab.

# filename: train_fraud_models.py
import os
import gc
import pandas as pd
import numpy as np
from pathlib import Path
import joblib
from typing import Dict, Tuple

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix, precision_recall_fscore_support
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

# Optional: XGBoost if installed (recommended for large tabular data)
try:
    from xgboost import XGBClassifier
    _has_xgb = True
except Exception:
    _has_xgb = False

# For plotting (optional)
import matplotlib.pyplot as plt
import seaborn as sns

# Make deterministic-ish
RANDOM_STATE = 42

df = pd.read_csv("Fraud.csv")  # change path if needed
print("Loaded rows:", len(df))
df.head()

print(df.info())
print(df.isnull().sum())
print("Fraud distribution:\n", df["isFraud"].value_counts(normalize=False))

df["payerdebited"] = df["oldbalanceOrg"] - df["newbalanceOrig"]
df["recievercredited"] = df["newbalanceDest"] - df["oldbalanceDest"]

# payer and receiver type (first char)
df["payer_type"] = df["nameOrig"].str[0]  # mostly 'C'
df["reciever_type"] = df["nameDest"].str[0]  # 'M' or 'C'

start = pd.to_datetime("2024-04-01")
df["datetime"] = start + pd.to_timedelta(df["step"], unit="h")
df["hour"] = df["datetime"].dt.hour
df["day_of_week"] = df["datetime"].dt.dayofweek
df["date"] = df["datetime"].dt.day

df_model = df.copy()

df_model["isFraud_business"] = df_model["isFraud"]
df_model["isFraud_label"] = np.where(df_model["amount"] > 200000, 1, df_model["isFraud_business"])

drop_cols = [
    "step", "datetime", "isFlaggedFraud",
    "nameOrig", "nameDest",
    # dropping raw balances to avoid leakage if you choose to; comment out if you want to keep them
    "oldbalanceOrg", "newbalanceOrig", "oldbalanceDest", "newbalanceDest"
]

for c in drop_cols:
    if c in df_model.columns:
        df_model.drop(columns=c, inplace=True)

print("Columns used:", df_model.columns.tolist())

df_model = df_model.dropna(subset=["isFraud", "payerdebited", "recievercredited"])

# Ensure target column exists
target = "isFraud_label"

# Replace infinities and NaNs before type conversion
df_model = df_model.replace([np.inf, -np.inf], np.nan)
df_model[target] = df_model[target].fillna(0)  # assume missing labels are non-fraud (0)

# Convert safely
df_model[target] = df_model[target].astype(int)

# Separate features and target
X = df_model.drop(columns=[target, "isFraud_business"], errors="ignore")
y = df_model[target]

print("✅ Cleaned successfully!")
print("X shape:", X.shape)
print("Target distribution:\n", y.value_counts())

# Cell 6 — Light cleaning & column types
# Convert categorical columns to strings
cat_cols = []
if "type" in X.columns:
    cat_cols.append("type")
if "payer_type" in X.columns:
    cat_cols.append("payer_type")
if "reciever_type" in X.columns:
    cat_cols.append("reciever_type")

# Ensure they are strings (so OneHotEncoder picks them up)
for c in cat_cols:
    X[c] = X[c].astype(str)

numeric_cols = [c for c in X.columns if c not in cat_cols]
print("Numeric cols:", numeric_cols)
print("Categorical cols:", cat_cols)

# Cell 7 — Train/validation split (stratified)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=RANDOM_STATE, stratify=y
)
print("Train shape:", X_train.shape, "Test shape:", X_test.shape)

# Cell 8 — Preprocessing pipelines
numeric_transformer = Pipeline(steps=[
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_cols),
        ("cat", categorical_transformer, cat_cols)
    ],
    verbose_feature_names_out=False
)

# Cell 9 — Models to train
models: Dict[str, Pipeline] = {}

# Random Forest (balanced)
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=16,
    class_weight="balanced",
    n_jobs=-1,
    random_state=RANDOM_STATE,
)
models["random_forest"] = Pipeline([("preprocessor", preprocessor), ("clf", rf)])

# Logistic Regression (as baseline)
lr = LogisticRegression(max_iter=1000, class_weight="balanced", n_jobs=-1)
models["logistic_regression"] = Pipeline([("preprocessor", preprocessor), ("clf", lr)])

# XGBoost if available (use scale_pos_weight to handle imbalance)
if _has_xgb:
    # compute scale_pos_weight
    pos = sum(y_train == 1)
    neg = sum(y_train == 0)
    scale_pos_weight = neg / max(pos, 1)
    xgb = XGBClassifier(
        n_estimators=400,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        use_label_encoder=False,
        eval_metric="logloss",
        scale_pos_weight=scale_pos_weight,
        n_jobs=-1,
        random_state=RANDOM_STATE
    )
    models["xgboost"] = Pipeline([("preprocessor", preprocessor), ("clf", xgb)])
else:
    print("XGBoost not installed — skipping XGBoost model.")

print(X.isna().sum()[X.isna().sum() > 0])

# Cell 10 — Train models (careful: this can take time on full dataset)
results = {}
for name, pipe in models.items():
    print(f"\nTraining {name} ...")
    pipe.fit(X_train, y_train)
    # Evaluate on test set
    y_pred = pipe.predict(X_test)
    if hasattr(pipe, "predict_proba"):
        y_prob = pipe.predict_proba(X_test)[:, 1]
    else:
        # Pipeline's classifier exists at step -1
        clf = pipe.named_steps["clf"]
        if hasattr(clf, "predict_proba"):
            y_prob = clf.predict_proba(pipe.named_steps["preprocessor"].transform(X_test))[:, 1]
        else:
            y_prob = pipe.named_steps["clf"].decision_function(pipe.named_steps["preprocessor"].transform(X_test))
            # scale to 0..1 via minmax (not ideal) — but most classifiers we use have predict_proba
            y_prob = (y_prob - y_prob.min()) / (y_prob.max() - y_prob.min() + 1e-9)

    auc = roc_auc_score(y_test, y_prob)
    report = classification_report(y_test, y_pred, digits=4, output_dict=True)
    print("ROC-AUC:", auc)
    print(pd.DataFrame(report).transpose())
    results[name] = {
        "auc": float(auc),
        "report": report,
        "model_obj": pipe
    }

    # Save each pipeline
    model_path = f"{name}_pipeline.joblib"
    joblib.dump(pipe, model_path)
    print("Saved:", model_path)

    # free some memory if needed
    gc.collect()

import joblib
import pandas as pd

# Load the trained XGBoost pipeline
model = joblib.load("xgboost_pipeline.joblib")

sample_tx = {
    "type": "TRANSFER",
    "amount": 250500.00,
    "payerdebited": 250500.00,
    "recievercredited": 0.0,
    "payer_type": "C",
    "reciever_type": "C",
    "hour": 14,
    "day_of_week": 2,
    "date": 13
}

# Convert dict to DataFrame (XGBoost expects DataFrame / 2D array)
df_tx = pd.DataFrame([sample_tx])

# ===== Step 0: Imports =====
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from xgboost import XGBClassifier
import joblib

# ===== Step 1: Load your dataset =====
df = pd.read_csv("Fraud.csv")

# ===== Step 2: Feature Engineering =====
# Compute debited/credited amounts
df["payerdebited"] = df["oldbalanceOrg"] - df["newbalanceOrig"]
df["recievercredited"] = df["newbalanceDest"] - df["oldbalanceDest"]

# Extract datetime features
df['datetime'] = pd.to_datetime('2024-04-01') + pd.to_timedelta(df['step'], unit='h')
df['hour'] = df['datetime'].dt.hour
df['day_of_week'] = df['datetime'].dt.dayofweek
df['date'] = df['datetime'].dt.day

# Payer/Receiver type
df["payer_type"] = df["nameOrig"].str[0]
df["reciever_type"] = df["nameDest"].str[0]

# Drop unnecessary columns
df_model = df.drop(columns=["step","datetime","isFlaggedFraud",
                            "nameOrig","nameDest",
                            "oldbalanceOrg","newbalanceOrig",
                            "oldbalanceDest","newbalanceDest"])

# Fill any NaN or inf
df_model = df_model.replace([np.inf, -np.inf], np.nan)
df_model = df_model.fillna(0)

# ===== Step 3: Define features & target =====
target = "isFraud"
numeric_cols = ['amount', 'payerdebited', 'recievercredited', 'hour', 'day_of_week', 'date']
categorical_cols = ['type', 'payer_type', 'reciever_type']

X = df_model[numeric_cols + categorical_cols]
y = df_model[target].astype(int)

# ===== Step 4: Build preprocessing + XGBoost pipeline =====
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_cols),
    ("cat", categorical_transformer, categorical_cols)
])

xgb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", XGBClassifier(use_label_encoder=False, eval_metric="logloss"))
])

# ===== Step 5: Train model =====
xgb_pipeline.fit(X, y)
print("✅ XGBoost pipeline trained successfully!")

# Save the pipeline
joblib.dump(xgb_pipeline, "xgboost_pipeline_fraud.pkl")
print("✅ Pipeline saved as 'xgboost_pipeline_fraud.pkl'")

# ===== Step 6: Predict function for new transactions =====
def predict_transaction(tx: dict):
    df_tx = pd.DataFrame([tx])
    pred = xgb_pipeline.predict(df_tx)[0]
    prob = xgb_pipeline.predict_proba(df_tx)[0][1]
    return {"isFraud": int(pred), "fraud_probability": float(prob)}

# ===== Step 7: Test prediction =====
sample_tx = {
    "type": "TRANSFER",
    "amount": 250500.00,
    "payerdebited": 250500.00,
    "recievercredited": 0.0,
    "payer_type": "C",
    "reciever_type": "C",
    "hour": 14,
    "day_of_week": 2,
    "date": 13
}

result = predict_transaction(sample_tx)
print("Prediction:", result)

# Sample transactions
sample_txs = [
    {
        "type": "TRANSFER",
        "amount": 250500.00,
        "payerdebited": 250500.00,
        "recievercredited": 0.0,
        "payer_type": "C",
        "reciever_type": "C",
        "hour": 14,
        "day_of_week": 2,
        "date": 13
    },
    {
        "type": "PAYMENT",
        "amount": 5000.00,
        "payerdebited": 5000.00,
        "recievercredited": 5000.00,
        "payer_type": "C",
        "reciever_type": "M",
        "hour": 10,
        "day_of_week": 0,
        "date": 5
    },
    {
        "type": "CASH_OUT",
        "amount": 100000.00,
        "payerdebited": 100000.00,
        "recievercredited": 0.0,
        "payer_type": "C",
        "reciever_type": "C",
        "hour": 18,
        "day_of_week": 4,
        "date": 20
    },
    {
        "type": "TRANSFER",
        "amount": 15000.00,
        "payerdebited": 15000.00,
        "recievercredited": 15000.00,
        "payer_type": "C",
        "reciever_type": "C",
        "hour": 9,
        "day_of_week": 6,
        "date": 28
    }
]

# Convert to DataFrame
df_tx = pd.DataFrame(sample_txs)

# Predict using pipeline
predictions = xgb_pipeline.predict(df_tx)
probabilities = xgb_pipeline.predict_proba(df_tx)[:,1]

# Show results
for i, tx in enumerate(sample_txs):
    print(f"Transaction {i+1}:")
    print(f"  Amount: {tx['amount']}, Type: {tx['type']}")
    print(f"  Prediction (isFraud): {predictions[i]}, Fraud Probability: {probabilities[i]:.6f}\n")

"""
